/* generated by Makefile */
#ifndef AUXV6_ROOTFS_CONFIG_H
#define AUXV6_ROOTFS_CONFIG_H
#define ROOTFS_TYPE_XV6FS 1
#define ROOTFS_TYPE_EXT2 2
#define CONFIG_LEGACY_XV6FS 0
#define ROOTFS_TYPE 2
#define ROOTFS_DEV 2
#endif
