/*
 * 6wm/6wm.c — main entry point and X event loop
 *
 * Startup sequence:
 *   1. XOpenDisplay
 *   2. Install error handler (detect existing WM via BadAccess)
 *   3. XSelectInput on root: SubstructureRedirect + SubstructureNotify
 *   4. atoms_init(), draw_init()
 *   5. Scan existing mapped windows (adopt pre-existing clients)
 *   6. Run event loop until g_wm.running == 0
 */

#include "6wm.h"
#include "atoms.h"
#include "client.h"
#include "draw.h"
#include "focus.h"
#include "frame.h"
#include "menu.h"
#include "stack.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

/* ------------------------------------------------------------------ *
 * Global state                                                        *
 * ------------------------------------------------------------------ */

WmGlobal g_wm;

/* ------------------------------------------------------------------ *
 * Error handling                                                      *
 * ------------------------------------------------------------------ */

static int g_another_wm;

static int
error_handler_check_wm(Display *dpy, XErrorEvent *e)
{
    (void)dpy;
    if (e->error_code == BadAccess)
        g_another_wm = 1;
    return 0;
}

static int
error_handler_default(Display *dpy, XErrorEvent *e)
{
        dprintf(2, "6wm: X error: code=%d request=%d resource=%lu\n",
            (int)e->error_code, (int)e->request_code,
            (unsigned long)e->resourceid);
        (void)dpy;
    /* Non-fatal: continue running */
    return 0;
}

/* ------------------------------------------------------------------ *
 * Event handlers                                                      *
 * ------------------------------------------------------------------ */

/*
 * MapRequest (§7.1) — client wants to map a new toplevel.
 */
static void
on_map_request(XMapRequestEvent *e)
{
    Client *c;

    /* Already managed? */
    c = client_find(e->window);
    if (c) {
        XMapWindow(g_wm.dpy, c->frame);
        return;
    }

    c = client_manage(e->window);

    if (!c) {
        /* Unmanaged or classify failure: let it map directly */
        XMapWindow(g_wm.dpy, e->window);
        return;
    }

    frame_create(c);
    if (!c->frame) {
        /* Frame creation failed; map client bare */
        XMapWindow(g_wm.dpy, c->win);
        client_unmanage(c);
        return;
    }

    /* §7.1 steps 6-7: map client then frame, set focus */
    XMapWindow(g_wm.dpy, c->win);
    XMapWindow(g_wm.dpy, c->frame);

    frame_draw(c);
    focus_set(c);
    stack_restack();
}

/*
 * ConfigureRequest (§7.2) — client requests a geometry or stacking change.
 */
static void
on_configure_request(XConfigureRequestEvent *e)
{
    Client        *c;

    c = client_find(e->window);

    if (c) {
        /* Managed: interpret through WM policy */
        int new_x = (e->value_mask & CWX)      ? e->x      : c->x;
        int new_y = (e->value_mask & CWY)      ? e->y      : c->y;
        int new_w = (e->value_mask & CWWidth)  ? e->width  : c->cw;
        int new_h = (e->value_mask & CWHeight) ? e->height : c->ch;
        frame_configure(c, new_x, new_y, new_w, new_h);
    } else {
        /* Unmanaged: pass through unchanged */
        XWindowChanges wc;
        wc.x            = e->x;
        wc.y            = e->y;
        wc.width        = e->width;
        wc.height       = e->height;
        wc.border_width = e->border_width;
        wc.sibling      = e->above;
        wc.stack_mode   = e->detail;
        XConfigureWindow(g_wm.dpy, e->window, e->value_mask, &wc);
    }
}

/*
 * UnmapNotify — client (or its frame) was unmapped.
 */
static void
on_unmap_notify(XUnmapEvent *e)
{
    Client *c;

    c = client_find(e->window);
    if (!c) return;

    /* Ignore synthetic unmaps generated by our own reparent (§7.1) */
    if (e->send_event) return;

    frame_destroy(c);
    client_unmanage(c);
    focus_revert();
    stack_restack();
}

/*
 * DestroyNotify — client window was destroyed.
 */
static void
on_destroy_notify(XDestroyWindowEvent *e)
{
    Client *c;

    c = client_find(e->window);
    if (!c) return;

    /* Frame may already be gone; clear to avoid double-destroy */
    c->frame = None;
    client_unmanage(c);
    focus_revert();
    stack_restack();
}

/*
 * ButtonPress — click-to-focus, drag initiation, and control actions.
 */
static void
on_button_press(XButtonEvent *e)
{
    Client *c;
    int     hit;

    c = client_find(e->window);
    if (!c) return;

    /* Focus and raise on any click (§6.1) */
    if (c != g_wm.focused)
        focus_set(c);

    /* Only handle button 1 for WM actions on the frame */
    if (e->window != c->frame || e->button != Button1)
        return;

    hit = frame_hittest(c, e->x, e->y);

    switch (hit) {

    case HITTEST_CLOSE:
        client_close(c);
        break;

    case HITTEST_ZOOM:
        /*
         * TODO(zoom): toggle between normal and policy-defined zoomed
         * geometry (§8 — zoom box semantics).
         */
        break;

    case HITTEST_DRAG:
        c->drag_mode    = DRAG_MOVE;
        c->drag_start_x = e->x_root;
        c->drag_start_y = e->y_root;
        c->drag_orig_x  = c->x;
        c->drag_orig_y  = c->y;
        XGrabPointer(g_wm.dpy, c->frame, False,
                     ButtonReleaseMask | PointerMotionMask,
                     GrabModeAsync, GrabModeAsync,
                     None, None, CurrentTime);
        break;

    case HITTEST_RESIZE:
        c->drag_mode    = DRAG_RESIZE;
        c->drag_start_x = e->x_root;
        c->drag_start_y = e->y_root;
        c->drag_orig_w  = c->cw;
        c->drag_orig_h  = c->ch;
        XGrabPointer(g_wm.dpy, c->frame, False,
                     ButtonReleaseMask | PointerMotionMask,
                     GrabModeAsync, GrabModeAsync,
                     None, None, CurrentTime);
        break;

    default:
        break;
    }
}

/*
 * ButtonRelease — end drag or resize.
 */
static void
on_button_release(XButtonEvent *e)
{
    Client *c;

    (void)e;

    /* End any active drag on the focused client */
    c = g_wm.focused;
    if (c && c->drag_mode != DRAG_NONE) {
        c->drag_mode = DRAG_NONE;
        XUngrabPointer(g_wm.dpy, CurrentTime);
    }
}

/*
 * MotionNotify — drag/resize update (§6.3).
 */
static void
on_motion_notify(XMotionEvent *e)
{
    Client *c;
    int     dx, dy;

    c = g_wm.focused;
    if (!c || c->drag_mode == DRAG_NONE)
        return;

    dx = e->x_root - c->drag_start_x;
    dy = e->y_root - c->drag_start_y;

    /* Only start moving once we've exceeded DRAG_THRESHOLD (§6.3) */
    if (dx * dx + dy * dy < DRAG_THRESHOLD * DRAG_THRESHOLD
        && c->drag_mode == DRAG_MOVE)
        return;

    if (c->drag_mode == DRAG_MOVE) {
        int nx = c->drag_orig_x + dx;
        int ny = c->drag_orig_y + dy;

        /* Clamp to screen bounds */
        if (nx < 0) nx = 0;
        if (ny < g_wm.menubar_h) ny = g_wm.menubar_h;
        if (nx + c->w > g_wm.sw) nx = g_wm.sw - c->w;
        if (ny + c->h > g_wm.sh) ny = g_wm.sh - c->h;

        c->x = nx;
        c->y = ny;
        XMoveWindow(g_wm.dpy, c->frame, nx, ny);

    } else if (c->drag_mode == DRAG_RESIZE) {
        int nw = c->drag_orig_w + dx;
        int nh = c->drag_orig_h + dy;
        int min_w = CTRL_MARGIN + 2 * CTRL_SIZE + CTRL_GAP + CTRL_MARGIN + 16;
        int min_h = 16;

        if (nw < min_w) nw = min_w;
        if (nh < min_h) nh = min_h;

        frame_configure(c, c->x, c->y, nw, nh);
    }
}

/*
 * Expose — redraw frame chrome.
 */
static void
on_expose(XExposeEvent *e)
{
    Client *c;

    /* Only redraw on the last Expose in a sequence */
    if (e->count > 0) return;

    c = client_find(e->window);
    if (c && c->frame == e->window)
        frame_draw(c);
}

/*
 * PropertyNotify — title change or AUX menu model/state update.
 */
static void
on_property_notify(XPropertyEvent *e)
{
    Client *c;

    c = client_find(e->window);
    if (!c) return;

    if (e->atom == XA_WM_NAME) {
        client_update_title(c);
        if (c->frame)
            frame_draw(c);
    }

    /* Forward menu-related property changes to the menubar */
    menu_on_property(c, e);
}

/*
 * ClientMessage — WM_DELETE replies, AUX_MENU_COMMAND.
 */
static void
on_client_message(XClientMessageEvent *e)
{
    /*
     * _AUX_MENU_COMMAND sent to the WM itself (should not normally
     * happen in v1, but handle defensively).
     */
    if ((Atom)e->message_type == g_wm.a_aux_menu_command) {
        menu_dispatch_command(e);
        return;
    }

    /*
     * Check for menubar registration: a window sends a known
     * registration message to root declaring itself the menubar.
     *
     * TODO(menu): define a formal registration atom/protocol.
     * For now, menubar registration is done via menu_register_bar()
     * called from a dedicated startup path.
     */
}

/* ------------------------------------------------------------------ *
 * Adopt pre-existing mapped windows at startup                        *
 * ------------------------------------------------------------------ */

static void
scan_existing_windows(void)
{
    Window        root_ret, parent_ret;
    Window       *children = NULL;
    unsigned int  nchildren, i;
    XWindowAttributes attrs;

    if (!XQueryTree(g_wm.dpy, g_wm.root,
                    &root_ret, &parent_ret,
                    &children, &nchildren))
        return;

    for (i = 0; i < nchildren; i++) {
        if (!XGetWindowAttributes(g_wm.dpy, children[i], &attrs))
            continue;
        if (attrs.override_redirect || attrs.map_state != IsViewable)
            continue;

        /* Adopt as a managed client */
        {
            Client *c = client_manage(children[i]);
            if (!c) continue;

            frame_create(c);
            if (!c->frame) { client_unmanage(c); continue; }

            XMapWindow(g_wm.dpy, c->win);
            XMapWindow(g_wm.dpy, c->frame);
            frame_draw(c);
        }
    }

    if (children)
        XFree(children);

    stack_restack();

    /* Focus the first document-layer window found */
    {
        Client *c;
        for (c = g_wm.clients; c; c = c->next) {
            if (c->layer == LAYER_DOCUMENT) {
                focus_set(c);
                break;
            }
        }
    }
}

/* ------------------------------------------------------------------ *
 * Event loop                                                          *
 * ------------------------------------------------------------------ */

static void
run(void)
{
    XEvent ev;

    while (g_wm.running) {
        XNextEvent(g_wm.dpy, &ev);

        switch (ev.type) {
        case MapRequest:
            on_map_request(&ev.xmaprequest);
            break;
        case ConfigureRequest:
            on_configure_request(&ev.xconfigurerequest);
            break;
        case UnmapNotify:
            on_unmap_notify(&ev.xunmap);
            break;
        case DestroyNotify:
            on_destroy_notify(&ev.xdestroywindow);
            break;
        case ButtonPress:
            on_button_press(&ev.xbutton);
            break;
        case ButtonRelease:
            on_button_release(&ev.xbutton);
            break;
        case MotionNotify:
            /* Coalesce: only process the latest motion event */
            while (XCheckTypedEvent(g_wm.dpy, MotionNotify, &ev))
                ;
            on_motion_notify(&ev.xmotion);
            break;
        case Expose:
            on_expose(&ev.xexpose);
            break;
        case PropertyNotify:
            on_property_notify(&ev.xproperty);
            break;
        case ClientMessage:
            on_client_message(&ev.xclient);
            break;
        default:
            break;
        }
    }
}

/* ------------------------------------------------------------------ *
 * main                                                                *
 * ------------------------------------------------------------------ */

int
main(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    memset(&g_wm, 0, sizeof(g_wm));

    g_wm.dpy = XOpenDisplay(NULL);
    if (!g_wm.dpy) {
        dprintf(2, "6wm: cannot open display\n");
        return 1;
    }

    g_wm.screen = DefaultScreen(g_wm.dpy);
    g_wm.root   = RootWindow(g_wm.dpy, g_wm.screen);
    g_wm.sw     = DisplayWidth(g_wm.dpy, g_wm.screen);
    g_wm.sh     = DisplayHeight(g_wm.dpy, g_wm.screen);

    /* Detect another running WM via BadAccess on SubstructureRedirectMask */
    g_another_wm = 0;
    XSetErrorHandler(error_handler_check_wm);
    XSelectInput(g_wm.dpy, g_wm.root,
                 SubstructureRedirectMask
                 | SubstructureNotifyMask
                 | ButtonPressMask
                 | PropertyChangeMask);
    XSync(g_wm.dpy, False);

    if (g_another_wm) {
        dprintf(2, "6wm: another window manager is already running\n");
        XCloseDisplay(g_wm.dpy);
        return 1;
    }

    XSetErrorHandler(error_handler_default);

    atoms_init();
    draw_init();

    g_wm.running = 1;

    scan_existing_windows();

    run();

    draw_fini();
    XCloseDisplay(g_wm.dpy);
    return 0;
}
