# Makefile.auxv6 - fvwm2 (fvwm2-stable) first-pass portability lane for auxv6/x6
#
# This lane is intentionally "non-first-class": configure/build pass only.
# Its primary purpose is to drive X11 gap discovery against our libX11
# implementation (user/x11.c / user/libX11.a).
#
# Expected usage:
#   make ports-sync
#   make PORTS=1 ports-progs
# or directly:
#   make -C ports/fvwm-fvwm2-stable -f Makefile.auxv6 all
#
# Output:
#   fvwm (ELF artifact, used by ports-progs install logic)
#   .auxv6-build/first-pass.log (compile+link transcript)

PORTS_COMMON_CALLER := $(lastword $(MAKEFILE_LIST))
include $(dir $(abspath $(PORTS_COMMON_CALLER)))../../config/ports-common.mk

SRCDIR  := $(realpath $(dir $(abspath $(PORTS_COMMON_CALLER))))
BUILDDIR := $(SRCDIR)/.auxv6-build
OUT     := $(SRCDIR)/_fvwm2
LOG     := $(BUILDDIR)/first-pass.log

# fvwm2 source subtrees to compile
FVWM_DIR := $(SRCDIR)/fvwm
LIBS_DIR := $(SRCDIR)/libs

# Enumerate all .c files under fvwm/ and libs/
# Exclude optional-feature files that require disabled deps (XRender, Xft,
# PNG, SVG, BIDI, readline, rplay, stroke, session-mgmt).
FVWM_EXCLUDE := %/session.c
LIBS_EXCLUDE := %/FRender.c %/FRenderInit.c %/Fft.c %/FBidi.c \
                %/Ficonv.c %/FGettext.c %/Fsvg.c %/Fpng.c %/Fxpm.c \
                %/FShm.c %/PictureImageLoader.c %/strcasecmp.c %/strncasecmp.c

FVWM_SRCS_ALL := $(shell find $(FVWM_DIR) -maxdepth 1 -type f -name '*.c' 2>/dev/null)
LIBS_SRCS_ALL := $(shell find $(LIBS_DIR) -maxdepth 1 -type f -name '*.c' 2>/dev/null)

FVWM_SRCS := $(filter-out $(FVWM_EXCLUDE),$(FVWM_SRCS_ALL))
LIBS_SRCS  := $(filter-out $(LIBS_EXCLUDE),$(LIBS_SRCS_ALL))
ALL_SRCS   := $(FVWM_SRCS) $(LIBS_SRCS)

TOOL_GCC_INCLUDE := $(shell $(CC) -print-file-name=include)

# Include paths: auxv6 headers first, then fvwm internal paths.
# -I$(SRCDIR) provides config.h; fvwm .c files do #include "config.h".
# -I$(SRCDIR)/libs is needed for fvwm/ sources that do #include "libs/Foo.h".
COMMON_CPPFLAGS := \
  -nostdinc \
  -I$(SRCDIR) \
  -I$(SRCDIR)/libs \
  -I$(SRCDIR)/fvwm \
  -I$(ROOT)/include \
  -I$(ROOT)/include/posix \
  -I$(ROOT)/include/posix/sys \
  -isystem $(TOOL_GCC_INCLUDE) \
  -DHAVE_CONFIG_H \
  -D__linux__=1 \
  -D_GNU_SOURCE \
  -DSTDC_HEADERS=1

COMMON_CFLAGS := \
  -fno-pic -static -fno-builtin -fno-strict-aliasing -O2 -Wall -m32 \
  -fno-stack-protector -std=gnu11 \
  -Wno-error=implicit-function-declaration \
  -Wno-error=implicit-int \
  -Wno-error=unused-but-set-variable \
  -Wno-error=parentheses \
  -Wno-error=switch \
  -Wno-error=int-conversion \
  -Wno-error=pointer-sign \
  -Wno-error=pointer-to-int-cast \
  -Wno-error=int-to-pointer-cast \
  -Wno-error=unused-result \
  -Wno-error=deprecated-declarations \
  -Wno-error=format \
  -Wno-error=stringop-truncation \
  -Wno-error=stringop-overflow

COMMON_LDFLAGS := \
  -m32 -no-pie -nostdlib -static \
  -Wl,--allow-multiple-definition \
  $(AUXV6_CRT0_OBJ)

LIBC_FALLBACK_A := $(ROOT)/targetfs/lib/libc.a
LIBC_LINK_A     := $(firstword $(wildcard $(AUXV6_LIBC_A)) $(wildcard $(LIBC_FALLBACK_A)))
PORT_LIBS       := $(AUXV6_AUXRT_A) $(AUXV6_X11_A) $(LIBC_LINK_A) $(LIBGCC)
TARGETFS_DIR    ?= $(ROOT)/targetfs
TARGETFS_USR_BIN := $(TARGETFS_DIR)/usr/bin

.PHONY: all clean first-pass check-host-contamination install-targetfs config-h

all: config-h first-pass $(OUT) check-host-contamination

# Emit config.h from the authoritative copy embedded here.
# This runs every build so a fresh ports-sync never leaves a stale or missing
# config.h.  The file is re-written only when content actually changes.
define FVWM_CONFIG_H
/* config.h - hand-crafted for auxv6 first-pass portability lane.            */
/* Authoritative source: ports/makefiles/fvwm2.Makefile (config-h target).   */
/* Do NOT edit this file directly; it will be overwritten on the next build.  */
/*                                                                            */
/* Strategy: enable only what auxv6 libX11 already provides; disable optional */
/* deps (XRender, Xft, PNG, SVG, BIDI, NLS, etc.) that would require missing  */
/* libraries.  Shape and Xinerama are enabled because our libX11 covers the   */
/* critical call sites (missing helpers are noted in the gap plan).           */
/*                                                                            */
/* Xft: fvwm2 uses ~60 Xft symbols; we currently export 23.  Re-enable       */
/* HAVE_XFT once XftInit, XftFontSet*, XftPattern{Add,Get,Dup,Find},         */
/* XftObjectSet*, XftListFonts*, XftNameParse and friends are implemented.    */
#ifndef FVWM_CONFIG_H
#define FVWM_CONFIG_H
/* Package identity */
#define PACKAGE       "fvwm"
#define VERSION       "2.6.9"
#define VERSIONINFO   "fvwm 2.6.9 (from fvwm2-stable branch)"
#define FVWM_CONFIG   "config"
#define FVWM2RC       ".fvwm2rc"

/* Pull in default constants used throughout fvwm headers/sources. */
#include "libs/defaults.h"

/* Common libc declarations needed by many fvwm units under auxv6. */
#include <stdlib.h>
#include <string.h>

/* auxv6 termios header expects speed_t to exist. */
#ifndef _SPEED_T_DEFINED
#define _SPEED_T_DEFINED
typedef unsigned int speed_t;
#endif

/* Pull termios once, then drop ECHO macro to avoid collision with fvwm's
 * message-level enum token named ECHO. Subsequent termios includes are
 * guarded and won't reintroduce it. */
#include <termios.h>
#ifdef ECHO
#undef ECHO
#endif
/* Default image search path */
#define FVWM_IMAGEPATH "/usr/share/fvwm/images:/usr/share/pixmaps"
/* POSIX / libc features present in auxv6 libc */
#define HAVE_X              1
#define HAVE_FCNTL_H        1
#define HAVE_SYS_STAT_H     1
#define HAVE_SYS_TIME_H     1
#define HAVE_SYS_SELECT_H   1
#define HAVE_SELECT         1
#define HAVE_ATEXIT         1
#define HAVE_GETHOSTNAME    1
#define HAVE_STRCASECMP     1
#define HAVE_STRNCASECMP    1
#define HAVE_STRERROR       1
#define HAVE_USLEEP         1
#define HAVE_WAITPID        1
#define HAVE_UNAME          1
#define HAVE_SETPGID        1
#define HAVE_SETPGRP        1
#define HAVE_SIGACTION      1
#define HAVE_SIGBLOCK       1
#define HAVE_SIGSETMASK     1
#define HAVE_SIGINTERRUPT   1
#define HAVE_INTTYPES_H     1
#define HAVE_STDINT_H       1
#define HAVE_GETPWUID       1
#define HAVE_UNSETENV       1
#define HAVE_SAFETY_MKSTEMP 1
/* X11 extensions: Shape YES, Xinerama YES */
#define SHAPE               1
#define HAVE_XINERAMA       1
/* Disabled optional deps for first-pass lane: */
/* HAVE_XRENDER  - 8 Render syms missing; re-enable after Tier-R gap work    */
/* HAVE_XFT      - 37/60 Xft syms missing; re-enable after Xft gap work      */
/* HAVE_XSHM     - SHM transport not implemented                              */
/* HAVE_XCURSOR  - Xcursor not ported                                         */
/* XPM / HAVE_PNG / HAVE_RSVG - image libs not ported                        */
/* HAVE_BIDI / HAVE_NLS / HAVE_ICONV - gettext/fribidi not ported            */
/* HAVE_STROKE / HAVE_READLINE / HAVE_RPLAY - optional input libs not ported */
/* SESSION - ICE/SM not ported                                                */
/* HAVE_XOUTPUT_METHOD - XOpenOM/XCloseOM not yet in libX11                  */
/* HAVE_RANDR - surfacing RandR holes via other WMs first                     */
#define HAVE_ADDED_ALPHA    0
#define HAVE_TINT           0
#define HAVE_UNIFORM_COLOR  0
#define HAVE_ICON_CSET      0
#define HAVE_ICONV_CHARSET  0
#define HAVE_LENGTH         0

/* configure feature toggles consumed directly by source */
#define FMiniIconsSupported 1
#define USEDECOR 1
#define FVWM_COLORSET_PRIVATE 1

/* Forward declarations for types used under FVWM_COLORSET_PRIVATE */
struct FvwmPictureThing;
typedef struct FvwmPictureThing FvwmPicture;

/* Debug no-op macros - must come before fvwm headers define their own */
#ifndef DBUG
#define DBUG(...) ((void)0)
#endif
#ifndef FEV_IS_EVENT_INVALID
#define FEV_IS_EVENT_INVALID(e) 0
#endif
#ifndef FEV_INVALIDATE_EVENT
#define FEV_INVALIDATE_EVENT(e) ((void)0)
#endif
#ifndef FEV_HAS_EVENT_WINDOW
#define FEV_HAS_EVENT_WINDOW(type) (1)
#endif

/* alloca via compiler builtin */
#ifndef alloca
#define alloca(s) __builtin_alloca(s)
#endif

/* fvwm_KeycodeToKeysym: wrapper around XKeycodeToKeysym */
#ifndef fvwm_KeycodeToKeysym
#define fvwm_KeycodeToKeysym(d, k, x, i) (XKeycodeToKeysym((d), (k), (i)))
#endif

/* install-path defines */
#ifndef FVWM_DATADIR
#define FVWM_DATADIR "/usr/share/fvwm"
#endif
#ifndef FVWM_CONFDIR
#define FVWM_CONFDIR "/etc/X11/fvwm"
#endif
#ifndef LOCALEDIR
#define LOCALEDIR "/usr/share/locale"
#endif

/* configure-ac compatibility shims used by fvwm libs */
typedef int fd_set_size_t;
#ifndef SUPPRESS_UNUSED_VAR_WARNING
#define SUPPRESS_UNUSED_VAR_WARNING(x) ((void)(x))
#endif
#ifndef RETSIGTYPE
#define RETSIGTYPE void
#endif
#ifndef SIGNAL_RETURN
#define SIGNAL_RETURN return
#endif
#ifndef SELECT_FD_SET_CAST
#define SELECT_FD_SET_CAST
#endif
#ifndef CLOCK_SKEW_MS
#define CLOCK_SKEW_MS 30000
#endif

#ifndef EXECUTABLE_EXTENSION
#define EXECUTABLE_EXTENSION NULL
#endif

#ifndef FVWM_MODULEDIR
#define FVWM_MODULEDIR "/usr/libexec/fvwm"
#endif

#ifndef STROKE_ARG
#define STROKE_ARG(x)
#endif
#ifndef STROKE_CODE
#define STROKE_CODE(x)
#endif

#ifndef min
#define min(a,b) ((a) < (b) ? (a) : (b))
#endif
#ifndef max
#define max(a,b) ((a) > (b) ? (a) : (b))
#endif

#endif /* FVWM_CONFIG_H */
endef
export FVWM_CONFIG_H

config-h: | $(SRCDIR)
	@new="$$FVWM_CONFIG_H"; \
	dest="$(SRCDIR)/config.h"; \
	if [ ! -f "$$dest" ] || [ "$$(cat "$$dest")" != "$$new" ]; then \
		printf '%s\n' "$$new" > "$$dest"; \
		echo "fvwm2: wrote config.h"; \
	fi

first-pass: config-h | $(BUILDDIR)
	@echo "fvwm2: starting first configure/build pass" > "$(LOG)"
	@if [ -z "$(ALL_SRCS)" ]; then \
		echo "fvwm2: no C sources found" | tee -a "$(LOG)" >&2; \
		exit 1; \
	fi
	@if [ -z "$(LIBC_LINK_A)" ]; then \
		echo "fvwm2: missing libc archive; expected $(AUXV6_LIBC_A) or $(LIBC_FALLBACK_A)" | tee -a "$(LOG)" >&2; \
		exit 1; \
	fi
	@set +e; \
	rc=0; \
	objs=""; \
	mkdir -p "$(BUILDDIR)/fvwm-objs" "$(BUILDDIR)/libs-objs"; \
	for src in $(FVWM_SRCS); do \
		base="$$(basename "$$src" .c)"; \
		obj="$(BUILDDIR)/fvwm-objs/$$base.o"; \
		if ! $(CC) $(COMMON_CPPFLAGS) $(COMMON_CFLAGS) -c "$$src" -o "$$obj" >>"$(LOG)" 2>&1; then \
			echo "  FAIL [fvwm] $$base.c" >> "$(LOG)"; \
			rc=1; \
		fi; \
		objs="$$objs $$obj"; \
	done; \
	for src in $(LIBS_SRCS); do \
		base="$$(basename "$$src" .c)"; \
		obj="$(BUILDDIR)/libs-objs/$$base.o"; \
		if ! $(CC) $(COMMON_CPPFLAGS) $(COMMON_CFLAGS) -c "$$src" -o "$$obj" >>"$(LOG)" 2>&1; then \
			echo "  FAIL [libs] $$base.c" >> "$(LOG)"; \
			rc=1; \
		fi; \
		objs="$$objs $$obj"; \
	done; \
	stubs_obj="$(BUILDDIR)/fvwm2-stubs.o"; \
	if ! $(CC) $(COMMON_CPPFLAGS) $(COMMON_CFLAGS) -I"$(SRCDIR)" \
		-c "$(ROOT)/ports/makefiles/fvwm2-stubs.c" \
		-o "$$stubs_obj" >>"$(LOG)" 2>&1; then \
		echo "  FAIL [stubs] fvwm2-stubs.c" >> "$(LOG)"; \
		rc=1; \
	fi; \
	objs="$$objs $$stubs_obj"; \
	if [ $$rc -eq 0 ]; then \
		$(CC) $(COMMON_LDFLAGS) $$objs $(PORT_LIBS) -o "$(BUILDDIR)/fvwm" >>"$(LOG)" 2>&1 || rc=$$?; \
	fi; \
	echo "fvwm2: first-pass make rc=$$rc" >> "$(LOG)"; \
	if [ $$rc -ne 0 ]; then \
		echo "fvwm2: first-pass portability failures recorded (non-fatal in staging lane)" >> "$(LOG)"; \
	fi
	@tail -120 "$(LOG)"

$(BUILDDIR):
	mkdir -p "$(BUILDDIR)"

$(OUT): first-pass
	@for cand in "$(BUILDDIR)/fvwm" "$(SRCDIR)/fvwm_bin"; do \
		if [ -f "$$cand" ] && $(OBJDUMP) -f "$$cand" 2>/dev/null | grep -q 'file format elf32-i386'; then \
			cp "$$cand" "$(OUT)"; \
			chmod 0755 "$(OUT)"; \
			exit 0; \
		fi; \
	done; \
	echo "fvwm2: no usable ELF binary produced (first-pass lane - expected during bringup)" >&2; \
	exit 1

check-host-contamination:
	@! grep -En '(^|[[:space:]])(cc|gcc|clang|i386-jos-elf-gcc)([[:space:]].*)?(-I|-isystem)[[:space:]]*(/usr/include|/usr/local/include|/opt/homebrew/include|/Library/Developer/CommandLineTools/usr/include|/Applications/Xcode.*/usr/include)' "$(LOG)" >/dev/null || \
		(echo "ERROR: host header path detected in fvwm2 port build log" >&2; \
		echo "Inspect $(LOG) for details." >&2; \
		exit 1)

install-targetfs: $(OUT)
	@install -d "$(TARGETFS_USR_BIN)"
	@install -m 0755 "$(OUT)" "$(TARGETFS_USR_BIN)/fvwm2"
	@echo "fvwm2: installed to $(TARGETFS_USR_BIN)/fvwm2"
	@install -d "$(TARGETFS_DIR)/usr/share/fvwm"
	@cd "$(SRCDIR)/default-config" && \
		find . -type d | while read d; do install -d "$(TARGETFS_DIR)/usr/share/fvwm/$$d"; done && \
		find . -type f | while read f; do install -m 0644 "$$f" "$(TARGETFS_DIR)/usr/share/fvwm/$$f"; done
	@install -d "$(TARGETFS_DIR)/etc/X11/fvwm"
	@echo "fvwm2: staged default-config to $(TARGETFS_DIR)/usr/share/fvwm"

clean:
	rm -rf "$(BUILDDIR)" "$(OUT)"
