// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_socket 22
#define SYS_bind   23
#define SYS_connect 24
#define SYS_send   25
#define SYS_recv   26
#define SYS_listen 27
#define SYS_accept 28
#define SYS_recvtimeout 29
#define SYS_sigsend 30
#define SYS_getppid 31
#define SYS_getpgrp 32
#define SYS_setpgid 33
#define SYS_setsid 34
#define SYS_waitpid 35
#define SYS_wait4 36
#define SYS_waitid 37
#define SYS_sigaction 38
#define SYS_tcsetpgrp 39
#define SYS_tcgetpgrp 40
#define SYS_sigprocmask 41
#define SYS_tcgetattr 42
#define SYS_tcsetattr 43
#define SYS_getuid 44
#define SYS_setuid 45
#define SYS_getgid 46
#define SYS_setgid 47
#define SYS_getcwd 48
#define SYS_chmod  49
#define SYS_chown  50
#define SYS_mountinfo 51
#define SYS_mount  52
#define SYS_umount 53
#define SYS_uname  54
#define SYS_stat   55
#define SYS_netifinfo 56
#define SYS_routeinfo 57
#define SYS_routeadd 58
#define SYS_devblocks 59
#define SYS_getdents 60
#define SYS_rename  61
#define SYS_ext2fail 62
#define SYS_fsfault 63
#define SYS_sigreturn 64
#define SYS_alarm 65
#define SYS_lseek 66
#define SYS_dup2 67
#define SYS_fcntl 68
#define SYS_netifsetaddr 69
#define SYS_arpinfo 70
